config/routes.rb
Gmaps::Application.routes.draw do

 

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

 
resources :events
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :event_details
  controller :event_details do
     get 'update_tweets' => :update_tweets
    post 'update_tweets' => :update_tweets
  end

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  get 'logout' => :destroy
  
  end
  

  resources :users
 

  resources :characters
  
  controller :characters do
    get 'user_markers' => :user_markers
    post 'user_markers' => :user_markers
   
  end
  
 
  
  controller :characters do
    get 'test' => :test
  end
 root :to => 'characters#index'

  

end

app/models/character.rb
class Character < ActiveRecord::Base
  
  attr_accessible :address, :gmaps, :latitude, :longitude, :name, :id, :user_id, :event_details_attributes, :event_details
  belongs_to :user, :inverse_of => :characters
  has_many :event_details, :dependent => :delete_all
  has_many :events, :dependent => :delete_all
  
  accepts_nested_attributes_for :event_details, :allow_destroy => true
  
  acts_as_gmappable
  
  validates_presence_of :name, :address
  

  def self.search(search, page)
    paginate :per_page => 5, :page =>page,
             :conditions => ['name like ? or address like ?', "%#{search}%", "%#{search}%"],
             :order => "created_at desc"
  end
  
  

  def gmaps4rails_address
    address
  end
  def gmaps4rails_infowindow
    "#{name} <br/> <a href='characters/#{id}'>more..</a>"# add here whatever html content you desire, it will be displayed when users clicks on the marker
    
       
  end
  def gmaps4rails_marker_picture
 {
  "picture" => "../images/marker.png",          # string,  mandatory
   "width" =>  "32",          # integer, mandatory
   "height" => "32"          # integer, mandatory

 }
 end
  
end


#Copyright 2012 Benjamin Roth
#
#Permission is hereby granted, free of charge, to any person obtaining
#a copy of this software and associated documentation files (the
#"Software"), to deal in the Software without restriction, including
#without limitation the rights to use, copy, modify, merge, publish,
#distribute, sublicense, and/or sell copies of the Software, and to
#permit persons to whom the Software is furnished to do so, subject to
#the following conditions:
#
#The above copyright notice and this permission notice shall be
#included in all copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
#EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
#NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
#LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


 
#Copyright (c) 2009 Mislav Marohnić
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of 
#this software and associated documentation files (the "Software"), to deal in 
#the Software without restriction, including without limitation the rights to 
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
#the Software, and to permit persons to whom the Software is furnished to do so, 
#subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all 
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS 
#FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
#COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
#IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
#CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  skip_before_filter :authorize, :only => [:index, :show]


  # GET /characters
  # GET /characters.json
  respond_to :json, :html
  def index
    @characters = Character.search(params[:search], params[:page])
    
    @json = Character.all.to_gmaps4rails
    @lines = Character.all
    @p = '['
   cnt = 1
   @lines.each do |line|
       lng = @lines.length
       a = '[{"lng": -2.2324901, "lat": 53.4677143}, {"lng": ' + line.longitude.to_s + ', "lat": ' + line.latitude.to_s + '}]'
       if cnt < lng
           a += ','
       end
       cnt += 1
       @p += a
   end
   @p += ']'
     respond_with @json
    
  end
  
  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end
  
  def user_markers
    
    @characters = Character.search(params[:search], params[:page])
    @characters = @characters.find_all_by_user_id(session[:user_id]) 
    
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])
    @character.user_id = session[:user_id]

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Marker was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.user_id == session[:user_id]
      if @character.update_attributes(params[:character])  
        format.html { redirect_to @character, notice: 'Marker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
      else 
        format.html { redirect_to @character, error: 'Permission denied!' }
        format.json { render json: @character.errors, status: :unprocessable_entity }
        
    end
  end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    if @character.event_details.any?
      @character.event_details.each do |e_d|
        e_d.destroy
      end
      @character.events.each do |e|
        e.destroy
      end
    end
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_event_detail_fields.html.erb
<fieldset>
<%= f.input :title %>
 <%= f.input :description, :input_html => { :class => 'input-xlarge', :rows => '5' }   %>
<%= f.input :from %>
  <%= f.input :to %>
</fieldset>

app/views/characters/_form.html.erb
<%= simple_form_for @character, :html => { :class => 'form-horizontal' } do |f| %>
<div class="field">
  
    <%= f.input :name %>
    <%= f.input :address %>

  </div>   
  <% if @character.event_details.any? %>
    <h4>Event Details</h4>
  <%end%>
      <%= f.fields_for :event_details do |builder| %>
      <%= render 'event_detail_fields', f: builder %>
    <% end %>

  
  


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                characters_path, :class => 'btn' %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<%- model_class = @character.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/index.html.erb
<%- model_class = Character.new.class -%>
<!-- 

gmaps and calendar


!-->
<div class="row">
  <div class="span9">
    <%= gmaps(
      "map_options" => {"auto_adjust" => "true", "bounds" => '[{"lat": 0, "lng": 0 }, {"lat": 80 , "lng": 100 }]'},
      "markers" => {"data" => @json,
        "options" => {"do_clustering" => true, "randomize" => true ,  "max_random_distance" => 10 }},
      "polylines" => {"data" => @p}
    ) %>  
  </div>
 
</div>
<br/>
<br/>
<!-- 
  
gmaps and calendar


!-->

<!-- 

>>>>>latest


!-->
<div class="offset3">
<ul class="nav nav-tabs">
  <li><a href="#tweets" data-toggle="tab">Latest Tweets</a></li>
  <li><a href="#pictures" data-toggle="tab">Latest Pictures</a></li>
  <li><a href="#videos" data-toggle="tab">Latest Videos</a></li>
  <li><a href="#blogs" data-toggle="tab">Latest Blogs</a></li>

</ul>
</div>
<div class="row">
  <div class="span3">
    
    <a href='/calendar' class="thumbnail" rel="tooltip"  title="Click to see all conferences and events in calendar view">
      <img src="assets/calendar.png" alt="calendar"/>
    </a>
  </div>  
  <div class="span9">
<div class="tab-content">
  
  <div class="tab-pane active" id="tweets">
    <table class="table table-striped">

      <%  tweets = Tweet.find(:all, :group => 'event_detail_id', :limit => 5, :order => 'created_at desc') %>

      <% tweets.each do |t| %>

        <tr><td>
            <blockquote>
              <%= t.content %>
              <div class="from">&mdash; @<%= t.screen_name %></div>
            </blockquote>
          </td>
          <td>
            <%= link_to "more..", event_detail_path(EventDetail.find(t.event_detail_id).character_id) %>
          </td></tr>

      <% end %>
    </table>
  </div>
  <div class="tab-pane" id="pictures">

    <% last_pictures = Picture.find(:all, :group => 'event_detail_id', :limit => 4, :order => 'created_at desc') %>
    <ul class="thumbnails">
      <% last_pictures.each do |lp| %>
        <li class="span3">
          <%  last_pics = Picture.check_url(lp.url)%>
          <%= content_tag :a, :href => "#{last_pics[0]}", :class => "thumbnail", :rel => "tooltip", :title => "#{last_pics[0]}"  do -%>
            <%= content_tag :img, :src => "#{last_pics[1]}"  do -%>

            <%end%>
          <%end%>
          <%= link_to "   more..", event_detail_path(EventDetail.find(lp.event_detail_id).character_id) %>
        </li>

      <%end%>
    </ul>
  </div>

  <div class="tab-pane" id="videos">
    <% last_videos = Video.find(:all, :group => 'event_detail_id', :limit => 4, :order => 'created_at desc') %>
    <ul class="thumbnails">
      <% last_videos.each do |lv| %>
        <li class="span3">
          <% if Video.is_youtube_url(lv.url)%>


            <%= content_tag :iframe, :width => "260", :height => "180", :src => "#{URI.extract(lv.url)[0]}", :frameborder =>"0", :class => "thumbnail" do %>
            <%end%>


          <% else %>

            <%= content_tag :img, :src => "assets/no_video.png", :rel => "tooltip", :title => "unavailable video", :class => "thumbnail"  do -%><%end%>

          <%end%>
          <%= link_to "   more..", event_detail_path(EventDetail.find(lv.event_detail_id).character_id) %>
        </li>

      <%end%>
    </ul>


  </div>

  <div class="tab-pane" id="blogs">
    <table class="table">

      <%  blogs = Blog.find(:all, :group => 'event_detail_id', :limit => 5, :order => 'created_at desc') %>

      <% blogs.each do |b| %>

        <tr><td>
            <blockquote>
              <%= b.url %>
            </blockquote>
          </td>
          <td>
            <%= link_to "more..", event_detail_path(EventDetail.find(b.event_detail_id).character_id) %>
          </td></tr>

      <% end %>
    </table>
  </div>
</div>
</div>
</div>
<br/>

<br/>
<!-- 

>>>>>>>>>>latest


!-->

<script type='text/javascript'>
  $(document).ready(function () {
    if ($("[rel=tooltip]").length) {
      $("[rel=tooltip]").tooltip({
        title: 'asdf'
      });
    }
  });
  
  
</script>






<div class="page-header">
  <h3>All events</h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <td colspan="4">
        <%= form_tag characters_path, :method => 'get', :class => 'navbar-search' do %>   
          <%= text_field_tag :search, params[:search], :class => 'span5', :placeholder => 'Type To Search Events' %>
        <% end %></td>

    </tr>
    <tr>

      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th>Author</th>
      <th></th>


    </tr>
  </thead>
  <tbody>
    <% counter = 0%>    
    <% @characters.each do |character| %>


      <tr>

        <td ><%= link_to character.name, character_path(character) %></td>
        <td><%= character.address %></td>

        <td><%= User.find(character.user_id).name %></td>

        <td>

          <%= content_tag :a, :href => "#myModal#{counter}",  :data => {:toggle => "modal"} do -%>
            See more
          <%end%>

          <%= content_tag :div, :class => "modal hide", :id => "myModal#{counter}" do -%>
            <%= content_tag :div, :class => "modal-header" do -%>
              <%= content_tag :button, :class => "close", :type => "button", :data => {:dismiss => "modal"} do -%>
                ×
              <% end  %>
              <%= content_tag :h3 do -%>
                <h4>Event: <%= @characters[counter].name %> </h4><span class="navbar brand">Location: <%= @characters[counter].address %></span>       


              <% end -%>
            <% end -%>

            <%= content_tag :div, :class => "modal-body" do -%>
              <%= content_tag :p do -%>



                <!-- nado sdes vse HTML TAGS zamenit s content_tag potomu 4to u vse odin i tot je href i id of div !-->

                <% if @characters[counter].event_details.any? %>

                  <% for e in @characters[counter].event_details %>
                    <h5><%= e.title %></h5>
                    <ul class="nav nav-tabs">
                      <li>

                        <%= content_tag :a, :href => "#modal-description#{counter}",  :data => {:toggle => "tab"} do -%>
                          Description
                        <%end%>
                      </li>
                      <li>
                        <%= content_tag :a, :href => "#modal-tweets#{counter}",  :data => {:toggle => "tab"} do -%>
                          Event Tweets
                        <%end%>

                      </li>
                      <li>
                        <%= content_tag :a, :href => "#modal-pictures#{counter}",  :data => {:toggle => "tab"} do -%>
                          Event Pictures
                        <%end%>

                      </li>
                      <li>
                        <%= content_tag :a, :href => "#modal-videos#{counter}",  :data => {:toggle => "tab"} do -%>
                          Event Videos
                        <%end%>

                      </li>
                      <li>
                        <%= content_tag :a, :href => "#modal-blogs#{counter}",  :data => {:toggle => "tab"} do -%>
                          Event Blogs
                        <%end%>

                      </li>

                    </ul>

                    <div class="tab-content">

                      <%= content_tag :div, :class => "tab-pane active", :id => "modal-description#{counter}" do -%>
                        <%= e.description %>  
                      <%end%>


                      <%= content_tag :div, :class => "tab-pane", :id => "modal-tweets#{counter}" do -%>
                        <%  if e.tweets.any? %>
                          <% e.tweets.each do |t| %>
                            <blockquote >
                              <p> <%= t.content %></p>
                              <small>@<%= t.screen_name %></small>
                            </blockquote>
                          <% end %>
                        <% else %>
                          <p>no tweets</p>
                        <% end %>
                      <%end%>


                      <%= content_tag :div, :class => "tab-pane", :id => "modal-pictures#{counter}" do -%>

                        <%  if e.pictures.any? %>
                          <ul class="thumbnails">
                            <% e.pictures.each do |p| %>

                              <% pictures = Picture.check_url(p.url)
                            %>

                              <%= content_tag :li,  :class => "span2"  do -%>


                                <%= content_tag :a, :href => "#{pictures[0]}", :class => "thumbnail", :rel => "tooltip", :title => "#{pictures[0]}"   do -%>
                                  <%= content_tag :img, :src => "#{pictures[1]}"  do -%>
                                  <%end%>
                                <%end%>
                              <%end%>
                            <%end%>
                          </ul>
                        <% else %>
                          <p>No pictures yet</p>
                        <% end %>

                      <%end%> 
                      <%= content_tag :div, :class => "tab-pane", :id => "modal-videos#{counter}" do -%>
                        <%  if e.videos.any? %>
                          <ul class="thumbnails">
                            <% e.videos.each do |v| %>

                              <%= content_tag :li, :class => "span3 thumbnail"  do -%>
                                <% if Video.is_youtube_url(v.url)%>


                                  <%= content_tag :iframe, :width => "260", :height => "180", :src => "#{URI.extract(v.url)[0]}", :frameborder =>"0" do %>
                                  <%end%>

                                <% else %>

                                  <%= content_tag :img, :src => "assets/no_video.png"  do -%><%end%>
                                <%end%>
                              <%end%>
                            <%end%> 
                          </ul>
                        <% else %>
                          <p>No videos yet</p>
                        <% end %>
                      <%end%>
                      <%= content_tag :div, :class => "tab-pane", :id => "modal-blogs#{counter}" do -%>
                        <%  if e.blogs.any? %>
                          <table class="table">
                            <% e.blogs.each do |b| %>

                              <tr><td>
                                  <blockquote>
                                    <%= b.url %>
                                  </blockquote>
                                </td>
                                <td>
                                  <%= link_to "more..", event_detail_path(EventDetail.find(b.event_detail_id).character_id) %>
                                </td></tr>

                            <% end %>
                          </table>            
                        <% else %>
                          <p>No blogs yet</p>
                        <% end %>

                      <%end%>
                    </div>

                  <% end %>

                <% else %>
                  <p>This event has no details yet.</p>
                <% end %>






              <% end -%>
            <% end -%>    
            <%= content_tag :div, :class => "modal-footer" do -%>
              <%= content_tag :a, :class => "btn", :href => '#', :data => {:dismiss => "modal"} do -%>
                close
              <% end -%>
            <% end -%>    

          <% end -%>

        </td>
      </tr>
      <%counter +=1%>
    <% end %>



  </tbody>
</table>

<%= will_paginate @characters%>












<%#*Copyright (c) 2006-2012 John Nunemaker, Wynn Netherland, Erik Michaels-Ober, Steve Richert%>
<%#*Permission is hereby granted, free of charge, to any person obtaining a copy of this software%> 
<%#*and associated documentation files (the "Software"), to deal in the Software without restriction,%> 
<%#*including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,%> 
<%#*and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,%> 
<%#*subject to the following conditions:%>
<%#*The above copyright notice and this permission notice shall be included in all copies or substantial%>
<%#*portions of the Software.%>
<%#*THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT%> 
<%#*LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.%>
<%#*IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,%>
<%#*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE%> 
<%#*SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.%>

app/views/characters/new.html.erb
<%- model_class = @character.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/characters/show.html.erb
<%- model_class = @character.class -%>
<div class="page-header">

  <h1>Event: <%= @character.name %> </h1><span class="navbar brand">Location: <%= @character.address %></span>
</div>

<div class="row ">
  <div class="span3 well">
    <div class="page-header"><h4>Details</h4></div>
    <dl class="dl-horizontal">

      <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
      <dd><%= @character.name %></dd>
      <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
      <dd><%= @character.address %></dd>
      <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
      <dd><%= @character.longitude %></dd>
      <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
      <dd><%= @character.latitude %></dd>
      <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
      <dd><%= User.find(@character.user_id).name %></dd>
    </dl>
  </div>
  <div class="span8">



    <% if @character.event_details.any? %>
      <% for event in @character.event_details %>
    <div class="page-header"><h3><%= event.title %></h3></div>
        
        <div class="accordion">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a href="#" data-toggle="collapse" data-target="#description">Description of the event</a>

            </div>
            <div id="description" class="accordion-body in collapse">
              <%= event.description  %>
            </div>
          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a href="#" data-toggle="collapse" data-target="#tweets">Tweets from academic about the event</a>
            </div>
            <div id="tweets" class="accordion-body collapse">
              <% if event.tweets.any? %>
                <% event.tweets.each do |t| %>
                  <blockquote>
                    <p> <%= t.content %></p>
                    <small>@<%= t.screen_name %></small>
                  </blockquote>
                <% end %>
              <% else %>
                <p>No tweets yet</p>
              <% end %>
            </div>

          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a href="#" data-toggle="collapse" data-target="#pictures">Pictures from academic of the event</a>
            </div>
            <div id="pictures" class="accordion-body collapse">

              
                <% if event.pictures.any? %>
              <ul class="thumbnails">
                  <% for picture in event.pictures %>
                    <% pictures = URI.extract(picture.url) %>
                    <%= content_tag :li,  :class => "span2"  do -%>


                      <%= content_tag :a, :href => "#{pictures[0]}", :class => "thumbnail"  do -%>
                        <%= content_tag :img, :src => "#{pictures[1]}"  do -%>

                        <%end%>
                      <%end%>
                    <%end%>

                  <% end %>
                </ul>
                <% else %>
                  <p>No pictures yet</p>
                <% end %>
              

            </div>

          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a href="#" data-toggle="collapse" data-target="#videos">Videos from academic of the event</a>
            </div>
            <div id="videos" class="accordion-body collapse">
                    <%  if event.videos.any? %>
      <ul class="thumbnails">
        <% event.videos.each do |v| %>
        
          <%= content_tag :li, :class => "span4 thumbnail"  do -%>
    <% if Video.is_youtube_url(v.url)%>
          
    
        <%= content_tag :iframe, :width => "260", :height => "180", :src => "#{URI.extract(v.url)[0]}", :frameborder =>"0" do %>
        <%end%>
          
        <% else %>
        
         <%= content_tag :img, :src => "assets/no_video.png"  do -%><%end%>
        <%end%>
        <%end%>
        <%end%> 
      </ul>
    <% else %>
      <p>No videos yet</p>
    <% end %>
            </div>
          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a href="#" data-toggle="collapse" data-target="#blogs">Blogs from academic of the event</a>
            </div>
            <div id="blogs" class="accordion-body collapse">
              
               <% if event.blogs.any? %>
                <% event.blogs.each do |b| %>
                  <blockquote>
                    <p> <%= b.url %></p>
                    
                  </blockquote>
                <% end %>
              <% else %>
                <p>No blogs yet</p>
              <% end %>
              
              
            </div>
          </div>
        </div>
      <%end%>
    <% else %>
      <p>This event has no info yet.</p>
    <% end %>


  </div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
    request.referer, :class => 'btn'  %>
  <%= link_to t('event_detail.show', :default => t("helpers.links.more_details")),
    event_detail_path(@character), :class => 'btn' %>

  <% if (session[:user_id] != nil && @character.user_id == session[:user_id]) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
      edit_character_path(@character), :class => 'btn' %>

    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
      character_path(@character),
      :method => 'delete',
      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
      :class => 'btn btn-danger pull-right' %>
  <% end%>

</div>

app/views/characters/user_markers.html.erb
<%- model_class = Character.new.class -%>
<div class="row">
  
  <div class="span9">
<%= form_tag user_markers_path, :method => 'get', :class => 'navbar-search pull-left' do %>
 
   
    <%= text_field_tag :search, params[:search], :class => 'span4', :placeholder => 'Search' %>
 
<% end %>
<P style="text-align: right">
<%= link_to t('.new', :default => t("helpers.links.create_new")),
            new_character_path,
            :class => 'btn btn-large btn-success'  %></p>

    <table class="table table-striped">
  <thead>
    <tr>
    
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th>Actions</th>
      
      
    </tr>
  </thead>
  <tbody>
    <% @characters.each do |character| %>
      <tr>
   
        <td><%= character.name %></td>
        <td><%= character.address %></td>
       
        
       
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
          character_path(character), :class => 'btn btn-mini btn-info'
          %>
          
          
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_character_path(character), :class => 'btn btn-mini' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              character_path(character),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      
    <% end %>
      
        
      
  </tbody>
</table>
  </div>
</div>

    
 


    
    
    <% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>
    