config/routes.rb
Gmaps::Application.routes.draw do

 

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

 
resources :events
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :event_details
  controller :event_details do
     get 'update_tweets' => :update_tweets
    post 'update_tweets' => :update_tweets
  end

  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  get 'logout' => :destroy
  
  end
  

  resources :users
 

  resources :characters
  
  controller :characters do
    get 'user_markers' => :user_markers
    post 'user_markers' => :user_markers
   
  end
  
 
  
  controller :characters do
    get 'test' => :test
  end
 root :to => 'characters#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <title>Academics Abroad</title>
    
    <%= stylesheet_link_tag "application"%>
 

    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "gmaps4rails" %>
    <%= javascript_include_tag "bootstrap-modal" %>
  
    
    


    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>




  </head>

  <body>
       <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-21225035-2']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
   
         <div class="container">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">Academics Abroad</a>
            <div class="nav-collapse">
              <ul class="nav">
                <li><%= link_to "Home", characters_path %></li>
                <%if User.find_by_id(session[:user_id])%>
                <li>
                  <%= link_to "My Profile", user_path(session[:user_id]) %>
                </li>
                <%end%>
                <li><%= link_to "My places", user_markers_path %></li>
                <li><%= link_to "Calendar", calendar_path %></li>
                
                <% if !User.find_by_id(session[:user_id]) %>

                  <li> 
                    <%=  link_to "Login", login_path%>
                  </li>
                <% else %>

                  <% if (session[:user_id] != nil && User.find(session[:user_id]).role_id == 1) %>
                    <li><%= link_to "Admin", admin_dashboard_path %></li>
                  <%  end %>
                  <li>
                    <%= link_to "Logout", logout_path %>
                  </li>
                <% end %>
<li><a href="/#" class="menulink">Contact Us</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
          <a class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
      
      <%= yield %>
      <%= yield :scripts %>
    
    
    </div>
     

  </body>
</html>